[build-system]
requires = ["setuptools>=42.0.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "src/napari_biom3d/_version.py"

[tool.black]
line-length = 79
target-version = ['py38', 'py39', 'py310']

[project]
name = "napari-biom3d"
version = "0.1.0"
dependencies = [
  "numpy",
  "magicgui",
  "qtpy",
  "scikit-image",
  "magicgui",
  "biom3d>=0.0.46",
  "paramiko",
  "omero-py",
  "netcat"
]
dynamic = ["description", "readme", "requires-python", "license", "authors", "classifiers", "urls"]



[project.optional-dependencies]
omero= [
    "paramiko",
    "omero-py",
    "netcat"
]

[tool.ruff]
line-length = 79
select = [
    "E", "F", "W", #flake8
    "UP", # pyupgrade
    "I", # isort
    "BLE", # flake8-blind-exception
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "C4", # flake8-comprehensions
    "ISC", # flake8-implicit-str-concat
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "SIM", # flake8-simplify
]
ignore = [
    "E501", # line too long. let black handle this
    "UP006", "UP007", # type annotation. As using magicgui require runtime type annotation then we disable this.
    "SIM117", # flake8-simplify - some of merged with statements are not looking great with black, reanble after drop python 3.9
]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*vendored*",
    "*_vendor*",
]

target-version = "py38"
fix = true
